CREATE DATABASE SAAS_REVENUE_INTELLIGENCE;
USE SAAS_REVENUE_INTELLIGENCE;
SHOW TABLES;
SELECT COUNT(*) FROM INVOICES;
SELECT COUNT(*) FROM PAYMENTS;
SELECT COUNT(*) FROM SUBSCRIPTIONS;
SELECT COUNT(*) FROM SUBSCRIPTION_PLANS;
SELECT COUNT(*) FROM PLAN_CHANGES;
SELECT COUNT(*) FROM CHURN_EVENTS;
SELECT COUNT(*) FROM CUSTOMERS;
/*Total Revenue*/
SELECT SUM(AMOUNT) AS TOTAL_REVENUE
FROM INVOICES WHERE STATUS='paid';

/*MRR*/
SELECT SUM(SP.PRICE) AS MRR
FROM SUBSCRIPTIONS S
JOIN SUBSCRIPTION_PLANS SP
ON S.PLAN_ID=SP.PLAN_ID
WHERE S.STATUS='active';

/*ARR*/
SELECT SUM(SP.PRICE)*12 AS ARR
FROM SUBSCRIPTIONS S
JOIN SUBSCRIPTION_PLANS SP
ON S.PLAN_ID=SP.PLAN_ID
WHERE S.STATUS='active';

/*EXECUTIVE KPI DASHBOARD*/
SELECT
(SELECT SUM(AMOUNT) FROM INVOICES
WHERE STATUS='paid') AS TOTAL_REVENUE,
(SELECT COUNT(DISTINCT CUSTOMER_ID)
	FROM CUSTOMERS) AS TOTAL_CUSTOMERS,
(SELECT COUNT(DISTINCT CUSTOMER_ID)
FROM SUBSCRIPTIONS WHERE STATUS='active') AS ACTIVE_CUSTOMERS,
(SELECT COUNT(DISTINCT CUSTOMER_ID)
FROM CHURN_EVENTS) AS CHURNED_CUSTOMERS;

/*Monthly Revenue Trend*/
SELECT
    DATE_FORMAT(INVOICE_DATE,'%Y-%m') AS MONTH,
    SUM(AMOUNT) AS REVENUE
FROM INVOICES
WHERE STATUS='paid'
GROUP BY MONTH
ORDER BY MONTH;

/*Revenue by Plan*/
SELECT SP.PLAN_NAME,
    SUM(I.AMOUNT) AS REVENUE
FROM INVOICES I
JOIN SUBSCRIPTIONS S
    ON I.CUSTOMER_ID = S.CUSTOMER_ID
JOIN SUBSCRIPTION_PLANS SP
    ON S.PLAN_ID = SP.PLAN_ID
WHERE I.STATUS='paid'
GROUP BY SP.PLAN_NAME
ORDER BY REVENUE DESC;

/*Revenue Share by Plan*/
SELECT
    SP.PLAN_NAME,
    ROUND(
        SUM(I.AMOUNT)*100/
        (SELECT SUM(AMOUNT)
         FROM INVOICES
         WHERE STATUS='paid'),
         2
    ) AS REVENUE_SHARE_PCT
FROM INVOICES I
JOIN SUBSCRIPTIONS S
    ON I.CUSTOMER_ID=S.CUSTOMER_ID
JOIN SUBSCRIPTION_PLANS SP
    ON S.PLAN_ID=SP.PLAN_ID
GROUP BY SP.PLAN_NAME;

/*Revenue by Country*/
SELECT C.COUNTRY,SUM(I.AMOUNT) AS REVENUE
FROM CUSTOMERS C JOIN INVOICES I
ON C.CUSTOMER_ID=I.CUSTOMER_ID
GROUP BY C.COUNTRY ORDER BY REVENUE DESC;

/*Revenue by Industry*/
SELECT C.INDUSTRY, SUM(I.AMOUNT) AS REVENUE FROM CUSTOMERS C
JOIN INVOICES I ON C.CUSTOMER_ID=I.CUSTOMER_ID
GROUP BY C.INDUSTRY ORDER BY REVENUE DESC;

/*INDUSTRY REVENUE SHARE*/
SELECT INDUSTRY,
ROUND(SUM(I.AMOUNT)*100/
(SELECT SUM(AMOUNT)
FROM INVOICES WHERE STATUS='paid'),2) AS REVENUE_SHARE_PCT
FROM CUSTOMERS C
JOIN INVOICES I
ON C.CUSTOMER_ID=I.CUSTOMER_ID
WHERE I.STATUS='paid'
GROUP BY INDUSTRY
ORDER BY REVENUE_SHARE_PCT DESC;

/*REVENUE BY COMPANY SIZE*/
SELECT C.COMPANY_SIZE,
SUM(I.AMOUNT) AS REVENUE
FROM CUSTOMERS C
JOIN INVOICES I
ON C.CUSTOMER_ID = I.CUSTOMER_ID
WHERE I.STATUS='paid'
GROUP BY C.COMPANY_SIZE
ORDER BY REVENUE DESC;

/*Revenue by Acquisition Channel*/
SELECT C.ACQUISITION_CHANNEL, SUM(I.AMOUNT) AS REVENUE
FROM CUSTOMERS C JOIN INVOICES I
ON C.CUSTOMER_ID=I.CUSTOMER_ID
GROUP BY C.ACQUISITION_CHANNEL
ORDER BY REVENUE DESC;

/*Top 10 Customers by Revenue*/
SELECT CUSTOMER_ID,
SUM(AMOUNT) AS REVENUE
FROM INVOICES GROUP BY CUSTOMER_ID
ORDER BY REVENUE DESC LIMIT 10;

/*Customer Lifetime Revenue*/
SELECT
    CUSTOMER_ID,
    COUNT(*) AS TOTAL_INVOICES,
    SUM(AMOUNT) AS LIFETIME_REVENUE
FROM INVOICES
GROUP BY CUSTOMER_ID;

/*CUSTOMER REVENUE RANKING*/
SELECT CUSTOMER_ID,SUM(AMOUNT) AS TOTAL_REVENUE,
RANK() OVER (ORDER BY SUM(AMOUNT) DESC) AS CUSTOMER_RANK
FROM INVOICES GROUP BY CUSTOMER_ID;

/*Customer Segmentation*/
 SELECT CUSTOMER_ID,
SUM(AMOUNT) AS TOTAL_REVENUE,
CASE WHEN SUM(AMOUNT) >= 1000 THEN 'HIGH VALUE'
     WHEN SUM(AMOUNT) >= 500 THEN 'MEDIUM VALUE'
ELSE 'LOW VALUE'
END AS CUSTOMER_SEGMENT
FROM INVOICES
GROUP BY CUSTOMER_ID;

/*AVERAGE REVENUE PER CUSTOMER*/
SELECT
    ROUND(
        SUM(AMOUNT) /
        COUNT(DISTINCT CUSTOMER_ID),
        2
    ) AS AVG_REVENUE_PER_CUSTOMER
FROM INVOICES
WHERE STATUS='paid';

/*Plan Mix Analysis*/
SELECT SP.PLAN_NAME,COUNT(*) AS CUSTOMERS
FROM SUBSCRIPTIONS S
JOIN SUBSCRIPTION_PLANS SP
ON S.PLAN_ID = SP.PLAN_ID
GROUP BY SP.PLAN_NAME
ORDER BY CUSTOMERS DESC;

/*Active vs Churned Customers*/
SELECT STATUS, COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMERS
FROM SUBSCRIPTIONS GROUP BY STATUS;

/*Churn by Reason*/
SELECT CHURN_REASON, COUNT(*) AS CHURN_COUNT
FROM CHURN_EVENTS GROUP BY CHURN_REASON ORDER BY CHURN_COUNT DESC;

/*CHURN SHARE BY REASON*/
SELECT
    CHURN_REASON,
    COUNT(*) AS CHURN_COUNT,
    ROUND(
        COUNT(*)*100/
        (SELECT COUNT(*) FROM CHURN_EVENTS),
        2
    ) AS CHURN_SHARE_PCT
FROM CHURN_EVENTS
GROUP BY CHURN_REASON
ORDER BY CHURN_COUNT DESC;

/*CHURN BY INDUSTRY*/
SELECT
    C.INDUSTRY,
    COUNT(DISTINCT CE.CUSTOMER_ID) AS CHURNED_CUSTOMERS
FROM CHURN_EVENTS CE
JOIN CUSTOMERS C
    ON CE.CUSTOMER_ID=C.CUSTOMER_ID
GROUP BY C.INDUSTRY
ORDER BY CHURNED_CUSTOMERS DESC;

/*MONTHLY CUSTOMER ACQUISITION*/
SELECT DATE_FORMAT(SIGNUP_DATE,'%Y-%m') AS MONTH,
COUNT(*) AS NEW_CUSTOMERS
FROM CUSTOMERS
GROUP BY MONTH
ORDER BY MONTH;

/*HIGH VALUE CUSTOMERS*/
SELECT CUSTOMER_ID,
SUM(AMOUNT) AS TOTAL_REVENUE
FROM INVOICES
GROUP BY CUSTOMER_ID
HAVING SUM(AMOUNT) > 1000
ORDER BY TOTAL_REVENUE DESC; 

/*Revenue Concentration Analysis*/
SELECT CUSTOMER_ID,
SUM(AMOUNT) AS REVENUE
FROM INVOICES
GROUP BY CUSTOMER_ID
ORDER BY REVENUE DESC LIMIT 20;

/*COUNTRY REVENUE SHARE*/
SELECT COUNTRY,
ROUND(SUM(I.AMOUNT)*100/
(SELECT SUM(AMOUNT)
FROM INVOICES WHERE STATUS='paid'),2)
AS REVENUE_SHARE_PCT
FROM CUSTOMERS C
JOIN INVOICES I
ON C.CUSTOMER_ID=I.CUSTOMER_ID
WHERE I.STATUS='paid'
GROUP BY COUNTRY
ORDER BY REVENUE_SHARE_PCT DESC;

/*Views (Low Risk, High Signal)*/
CREATE VIEW CUSTOMER_REVENUE AS
SELECT CUSTOMER_ID,
SUM(AMOUNT) AS TOTAL_REVENUE
FROM INVOICES GROUP BY CUSTOMER_ID;














